services:
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - mynetwork

  docling-serve:
    image: ghcr.io/ds4sd/docling-serve-cu124:latest
    container_name: docling-serve
    restart: always
    ports:
      - "127.0.0.1:5001:5001"
    networks:
      - mynetwork

  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1
    restart: unless-stopped
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      - database
      - docling-serve
    container_name: open-health
    volumes:
      - app_data:/app/public/uploads
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  app_data:
  ollama:
