# Development override for faster builds
services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      target: builder  # Stop at builder stage for development
      cache_from:
        - node:lts-alpine
      args:
        - BUILDKIT_INLINE_CACHE=1
        - OLLAMA_URL=${OLLAMA_URL}
        - DOCLING_URL=${DOCLING_URL}
    volumes:
      # Mount source code for hot reloading in development
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev